import Std.Http.Server
import SQLite
import Html
import Routing
import Forms
import Todo

open Std Async
open Std Http Server
open Html
open Routing
open Forms

/-- Every handler below is generic over `{Urls} [Todo.HasUrls Urls]` rather than a concrete URL
struct: `AppUrls` (generated by `application` below, `Routing/Application.lean`) doesn't exist
until that invocation runs, but these handlers are referenced *inside* its tree, so they must
already be fully elaborated beforehand -- `docs/application-macro-plan.md`'s Phase 3 notes. The
`deriving Todo.HasUrls` clause on `application` below is what supplies the concrete instance these
generic signatures get instantiated against. -/

def render {Urls : Type} [Todo.HasUrls Urls] (db : SQLite) (urls : Urls) (filter : Todo.Filter)
    (renderHtml : Urls → Array Todo.Item → Array Todo.Item → Todo.Filter → String) :
    ContextAsync (Response Body.Any) := do
  let items ← Todo.list db filter
  let allItems ← Todo.list db .all
  Response.ok.html (renderHtml urls items allItems filter)

/-- Renders the fragment for the filter the client's currently viewing (`HX-Current-URL`) --
what every mutating route responds with. -/
def renderMutation {Urls : Type} [Todo.HasUrls Urls] (db : SQLite) (urls : Urls)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) :=
  let currentFilter := match req.line.headers.get? (.ofString! "hx-current-url") with
  | some v => Todo.filterFromPath v.value
  | none => .all
  render db urls currentFilter Todo.mutationFragment

def pageHandler {Urls : Type} [Todo.HasUrls Urls] (filter : Todo.Filter) (ctx : SQLite)
    (urls : Urls) (_req : Request Body.Stream) : ContextAsync (Response Body.Any) :=
  render ctx urls filter Todo.page

def addHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  let title ← formField req "title"
  Todo.add ctx title
  renderMutation ctx urls req

/-- Swaps one todo's `<li>` into edit mode. Not a mutation (nothing in the DB changes), so unlike
every other route below it targets and returns just that one item, not the whole list section. -/
def editHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls) (id : Nat)
    (_req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  let items ← Todo.list ctx .all
  match items.find? (fun item => item.id == Int64.ofNat id) with
  | some item => Response.ok.html (Node.render (Todo.itemEditView urls item))
  | none => Response.notFound.text "Not Found"

def saveHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls) (id : Nat)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  let title ← formField req "title"
  Todo.setTitle ctx (Int64.ofNat id) title
  renderMutation ctx urls req

def toggleHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls) (id : Nat)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  Todo.toggle ctx (Int64.ofNat id)
  renderMutation ctx urls req

def deleteHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls) (id : Nat)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  Todo.delete ctx (Int64.ofNat id)
  renderMutation ctx urls req

def toggleAllHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  Todo.toggleAll ctx
  renderMutation ctx urls req

def clearCompletedHandler {Urls : Type} [Todo.HasUrls Urls] (ctx : SQLite) (urls : Urls)
    (req : Request Body.Stream) : ContextAsync (Response Body.Any) := do
  Todo.clearCompleted ctx
  renderMutation ctx urls req

application app : SQLite deriving Todo.HasUrls where
  "/" as index { get => pageHandler .all }
  "/active" as active { get => pageHandler .active }
  "/completed" as completed { get => pageHandler .completed }
  "/todos" as todos {
    post => addHandler
    "/:id:Nat" as todo {
      put => saveHandler
      delete => deleteHandler
      "/edit" as todoEdit { get => editHandler }
      "/toggle" as todoToggle { post => toggleHandler }
    }
    "/toggle-all" as toggleAll { post => toggleAllHandler }
    "/completed" as clearCompleted { delete => clearCompletedHandler }
  }

/-! ## Regression against the *real* generated `app`, not just `Routing.Application`'s toy harness

Confirms `application`'s concrete claim (`docs/application-macro-plan.md` §1) for this app's actual
patterns, and -- since nothing in `TodoTests` otherwise exercises HTTP dispatch -- that the real
route table and the real `Urls` values agree, the same way `Routing.Application`'s own `#eval
runGroup` regressions do (`Routing/Application.lean`). -/

#guard app.urls.index = "/"
#guard app.urls.active = "/active"
#guard app.urls.completed = "/completed"
#guard app.urls.todos = "/todos"
#guard app.urls.todo 7 = "/todos/7"
#guard app.urls.todoEdit 7 = "/todos/7/edit"
#guard app.urls.todoToggle 7 = "/todos/7/toggle"
#guard app.urls.toggleAll = "/todos/toggle-all"
#guard app.urls.clearCompleted = "/todos/completed"

open Std.Http.Internal.Test in
private def freshAppHandler : IO TestHandler := do
  let db ← SQLite.open ":memory:"
  Todo.initSchema db
  pure (app.handler db).onRequest

open Std.Http.Internal.Test in
#eval runGroup "Main.app" do
  let handler ← freshAppHandler
  checkClose "index page renders" (mkGet "/") handler (assertContains · "todos")
  checkClose "add dispatches through the real flattened route table" (mkPost "/todos" "title=Buy+milk")
    handler (assertContains · "Buy milk")
  checkClose "toggle-all beats the same-arity /:id:Nat capture" (mkPost "/todos/toggle-all" "")
    handler (fun r => assertStatus r "HTTP/1.1 200")

def main : IO Unit := Async.block do
  let db ← SQLite.open ":memory:"
  Todo.initSchema db
  let addr := .v4 ⟨.ofParts 127 0 0 1, 2000⟩
  serve addr (app.handler db) >>= waitShutdown
